package entities.auth;

public class DisplayUser implements AbstractUser {
  private final String uid;
  private final String name;

  public DisplayUser(String uid, String name) {
    this.uid = uid;
    this.name = name;
  }

  /**
   * @return the user's unique identifier, generated by Firebase
   */
  public String getUid() {
    return uid;
  }

  public String getName() {
    return name;
  }
}
